"""
Visual regression tests for the phone case rendering pipeline.

These tests verify structural and visual properties of rendered case
images, using deterministic comparison and reasonable tolerances rather
than fragile byte equality.

The tests load the real iPhone 17e template and render all three fixture
artworks, checking:
  - output dimensions
  - case body presence (non-transparent silhouette)
  - camera module protection
  - print region coverage (including rounded corners)
  - shadow layer correctness (below base, not darkening case body)
  - template reuse without modifications
  - deterministic re-render equality
  - visual regression against saved PNG baselines

Baseline strategy:
  Reference images are small PNG files under tests/fixtures/baselines/.
  They are NOT auto-generated by the test suite — baseline regeneration
  is an explicit developer action via scripts/regenerate_case_baselines.py.
  This prevents CI from silently blessing a changed renderer.
"""

import os
import warnings
import numpy as np
import pytest
from PIL import Image

from core.case_template_loader import load_case_template
from core.case_renderer import render_case


# ─── Paths ────────────────────────────────────────────────────────────────

TEMPLATE_DIR = os.path.join(
    os.path.dirname(__file__), "..",
    "assets", "case_templates", "apple", "iphone-17e", "hard", "rear",
)
TEMPLATE_JSON = os.path.join(TEMPLATE_DIR, "template.json")

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures", "artworks")
BASELINE_DIR = os.path.join(os.path.dirname(__file__), "fixtures", "baselines")

ARTWORKS = [
    ("color-block", "color-block.png", "cover"),
    ("tile-pattern", "tile-pattern.png", "tile"),
    ("transparent-artwork", "transparent-artwork.png", "cover"),
]

# Tolerance for visual comparison (mean absolute difference per channel)
VISUAL_TOLERANCE = 3.0  # out of 255

# Template geometry constants (matching generate_iphone17e_template.py)
CASE_X, CASE_Y = 315, 25
CASE_W, CASE_H = 970, 1950
CORNER_R = 150
BEZEL = 20
PRINT_X = CASE_X + BEZEL
PRINT_Y = CASE_Y + BEZEL
PRINT_W = CASE_W - 2 * BEZEL
PRINT_H = CASE_H - 2 * BEZEL
PRINT_CORNER_R = CORNER_R - BEZEL  # 130

# Camera geometry (new single-lens layout)
LENS_CX = CASE_X + int(CASE_W * 0.22)
LENS_CY = CASE_Y + int(CASE_H * 0.13)
LENS_RADIUS = 70
LENS_RING_WIDTH = 12
CAM_EXCLUDE_PAD = 18


# ─── Helper ───────────────────────────────────────────────────────────────

def _pixel(arr, x, y):
    """Return pixel at (x, y) as int16 array to avoid uint8 overflow."""
    return arr[y, x].astype(np.int16)


def _color_distance(p1, p2):
    """Mean absolute channel difference between two int16 pixels."""
    return np.abs(p1[:3] - p2[:3]).mean()


# ─── Fixtures ─────────────────────────────────────────────────────────────

@pytest.fixture
def template():
    return load_case_template(TEMPLATE_JSON)


@pytest.fixture(scope="module")
def rendered_outputs():
    """Render all three artworks once and cache for the module."""
    tpl = load_case_template(TEMPLATE_JSON)
    outputs = {}
    for name, filename, fit_mode in ARTWORKS:
        art_path = os.path.join(FIXTURES_DIR, filename)
        art = Image.open(art_path).convert("RGBA")
        result = render_case(art, tpl, template_dir=TEMPLATE_DIR, fit_mode=fit_mode)
        outputs[name] = np.array(result)
    return outputs


# ─── Structural tests ───────────────────────────────────────────────────────

class TestVisualStructure:

    def test_all_outputs_have_correct_dimensions(self, rendered_outputs, template):
        """Every rendered artwork must match the template canvas size."""
        for name, arr in rendered_outputs.items():
            assert arr.shape[1] == template.canvas.width, \
                f"{name}: width {arr.shape[1]} != {template.canvas.width}"
            assert arr.shape[0] == template.canvas.height, \
                f"{name}: height {arr.shape[0]} != {template.canvas.height}"

    def test_all_outputs_are_rgba(self, rendered_outputs):
        """Every output must have 4 channels (RGBA)."""
        for name, arr in rendered_outputs.items():
            assert arr.shape[2] == 4, f"{name}: expected 4 channels, got {arr.shape[2]}"

    def test_output_is_not_blank(self, rendered_outputs):
        """No output should be entirely transparent."""
        for name, arr in rendered_outputs.items():
            alpha = arr[:, :, 3]
            assert alpha.max() > 0, f"{name}: output is blank (fully transparent)"

    def test_output_is_not_fully_opaque(self, rendered_outputs):
        """Output should have some transparent pixels (outside case body)."""
        for name, arr in rendered_outputs.items():
            alpha = arr[:, :, 3]
            assert alpha.min() == 0, \
                f"{name}: expected some transparent pixels outside case body"


# ─── Silhouette tests ─────────────────────────────────────────────────────

class TestSilhouette:

    def test_case_body_present(self, rendered_outputs, template):
        """The case body silhouette should be present."""
        for name, arr in rendered_outputs.items():
            cx, cy = template.canvas.width // 2, template.canvas.height // 2
            assert arr[cy, cx, 3] > 128, \
                f"{name}: center of canvas should be opaque (case body)"

    def test_corners_are_transparent(self, rendered_outputs, template):
        """Canvas corners should be transparent (outside rounded case body)."""
        w, h = template.canvas.width, template.canvas.height
        corners = [(0, 0), (0, h - 1), (w - 1, 0), (w - 1, h - 1)]
        for name, arr in rendered_outputs.items():
            for cx, cy in corners:
                assert arr[cy, cx, 3] == 0, \
                    f"{name}: corner ({cx},{cy}) should be transparent"


# ─── Print region rounded corner tests (BLOCKER 4) ───────────────────────

class TestPrintRegionCorners:
    """Verify artwork does not leak into the rounded corners of the print region.

    The print mask is the intersection of a rounded print rectangle,
    the case body silhouette, and camera exclusion. At the four
    corners of the print-region bounding box, pixels should fall
    outside the rounded printable area and show base/overlay only —
    not artwork.
    """

    def _corner_point(self, corner_name):
        """Return (x, y) of a point in the rounded-corner annulus.

        The point must be:
          - INSIDE the case body silhouette (on the physical case)
          - OUTSIDE the print region rounded corner (no artwork here)

        Since case body corner and print region corner are concentric
        (radii CORNER_R=150 and PRINT_CORNER_R=130), we pick a point
        in the 20px-wide annulus between them, at ~140px from the
        arc center (45 degree angle from corner).
        """
        # Distance from arc center: halfway between print radius and case radius
        r = (PRINT_CORNER_R + CORNER_R) // 2  # ~140px
        # 45 degree offset from the corner vertex
        offset = int(r * 0.707)  # r * sin(45°) = r / sqrt(2)

        if corner_name == "top-left":
            arc_cx = PRINT_X + PRINT_CORNER_R  # same as case arc cx
            arc_cy = PRINT_Y + PRINT_CORNER_R  # same as case arc cy
            return arc_cx - offset, arc_cy - offset
        elif corner_name == "top-right":
            arc_cx = PRINT_X + PRINT_W - PRINT_CORNER_R
            arc_cy = PRINT_Y + PRINT_CORNER_R
            return arc_cx + offset, arc_cy - offset
        elif corner_name == "bottom-left":
            arc_cx = PRINT_X + PRINT_CORNER_R
            arc_cy = PRINT_Y + PRINT_H - PRINT_CORNER_R
            return arc_cx - offset, arc_cy + offset
        elif corner_name == "bottom-right":
            arc_cx = PRINT_X + PRINT_W - PRINT_CORNER_R
            arc_cy = PRINT_Y + PRINT_H - PRINT_CORNER_R
            return arc_cx + offset, arc_cy + offset
        else:
            raise ValueError(f"Unknown corner: {corner_name}")

    def test_top_left_corner_no_artwork_leak(self, rendered_outputs):
        """Top-left rounded corner of print region should not show artwork color.

        The color-block artwork has red in its top-left quadrant.
        If artwork leaked through the rounded corner, the corner
        pixel would be bright red. With proper masking, it should
        be a neutral case-edge color (not saturated red).
        """
        px, py = self._corner_point("top-left")

        for name, arr in rendered_outputs.items():
            pixel = _pixel(arr, px, py)
            # Pixel should be opaque (on the case body rim/bezel area)
            assert pixel[3] > 50, \
                f"{name}: top-left print corner should be on case body"
            # Pixel should NOT be saturated artwork color
            # For color-block top-left = red: R should not be much higher than G/B
            if name == "color-block":
                r, g, b = pixel[:3]
                # If artwork leaked, R >> G and R >> B
                assert not (r > 150 and r - g > 60), \
                    (f"{name}: top-left corner appears to have red artwork "
                     f"leak (r={r}, g={g}, b={b})")

    def test_top_right_corner_no_artwork_leak(self, rendered_outputs):
        """Top-right rounded corner should not show teal artwork leak.

        Color-block top-right quadrant is teal/green.
        """
        px, py = self._corner_point("top-right")

        for name, arr in rendered_outputs.items():
            pixel = _pixel(arr, px, py)
            assert pixel[3] > 50, \
                f"{name}: top-right print corner should be on case body"
            if name == "color-block":
                r, g, b = pixel[:3]
                # Teal leak would show G >> R
                assert not (g > 150 and g - r > 60), \
                    (f"{name}: top-right corner appears to have teal artwork "
                     f"leak (r={r}, g={g}, b={b})")

    def test_bottom_left_corner_no_artwork_leak(self, rendered_outputs):
        """Bottom-left rounded corner should not show yellow artwork leak.

        Color-block bottom-left quadrant is yellow/gold.
        """
        px, py = self._corner_point("bottom-left")

        for name, arr in rendered_outputs.items():
            pixel = _pixel(arr, px, py)
            assert pixel[3] > 50, \
                f"{name}: bottom-left print corner should be on case body"
            if name == "color-block":
                r, g, b = pixel[:3]
                # Yellow leak would show R and G both high, B low
                assert not (r > 150 and g > 150 and b < 120), \
                    (f"{name}: bottom-left corner appears to have yellow "
                     f"artwork leak (r={r}, g={g}, b={b})")

    def test_bottom_right_corner_no_artwork_leak(self, rendered_outputs):
        """Bottom-right rounded corner should not show blue artwork leak.

        Color-block bottom-right quadrant is navy blue.
        """
        px, py = self._corner_point("bottom-right")

        for name, arr in rendered_outputs.items():
            pixel = _pixel(arr, px, py)
            assert pixel[3] > 50, \
                f"{name}: bottom-right print corner should be on case body"
            if name == "color-block":
                r, g, b = pixel[:3]
                # Navy blue leak would show B >> R
                assert not (b > 100 and b - r > 40), \
                    (f"{name}: bottom-right corner appears to have blue "
                     f"artwork leak (r={r}, g={g}, b={b})")

    def test_center_of_print_region_has_artwork(self, rendered_outputs):
        """Sanity check: print region interior should show artwork.

        Samples at 25% of the print region (well inside the colored
        area, away from the center crosshair of test artworks).
        """
        cx = PRINT_X + int(PRINT_W * 0.25)
        cy = PRINT_Y + int(PRINT_H * 0.25)
        base_color = np.array([248, 247, 245], dtype=np.int16)

        for name, arr in rendered_outputs.items():
            pixel = _pixel(arr, cx, cy)
            assert pixel[3] > 128, \
                f"{name}: print region interior should be opaque"
            diff = _color_distance(pixel, base_color)
            assert diff > 10, \
                (f"{name}: print region interior should show artwork, "
                 f"but looks like bare base (diff={diff:.1f})")


# ─── Camera module tests (updated for new single-lens layout) ─────────────

class TestCameraModule:
    """Verify camera/lens/flash/mic regions are protected from artwork."""

    def test_lens_center_is_dark(self, rendered_outputs):
        """The camera lens center should be dark (not artwork color)."""
        for name, arr in rendered_outputs.items():
            pixel = _pixel(arr, LENS_CX, LENS_CY)
            brightness = pixel[:3].mean()
            assert brightness < 100, \
                f"{name}: lens center brightness {brightness} too high"

    def test_lens_region_not_artwork_color(self, rendered_outputs):
        """Lens area should not show bright saturated artwork colors."""
        # Sample several points inside lens area
        sample_points = [
            (LENS_CX, LENS_CY),
            (LENS_CX + 20, LENS_CY),
            (LENS_CX - 20, LENS_CY + 20),
        ]
        for name, arr in rendered_outputs.items():
            for sx, sy in sample_points:
                pixel = _pixel(arr, sx, sy)
                # No primary color channel should be > 150 (not bright artwork)
                assert pixel[0] < 150 and pixel[1] < 150 and pixel[2] < 150, \
                    f"{name}: lens point ({sx},{sy}) has bright pixel {pixel[:3]}"

    def test_flash_region_not_artwork(self, rendered_outputs):
        """Flash region should show flash housing, not artwork."""
        # Flash center
        flash_cx = LENS_CX + 140
        flash_cy = LENS_CY - 20
        for name, arr in rendered_outputs.items():
            pixel = _pixel(arr, flash_cx, flash_cy)
            # Flash should be light/neutral, not saturated artwork color
            # R, G, B should all be fairly high (light housing)
            assert pixel[0] > 150 and pixel[1] > 150, \
                f"{name}: flash region looks dark/incorrect: {pixel[:3]}"

    def test_camera_exclusion_in_print_mask(self, template):
        """Print mask should exclude camera lens region."""
        from PIL import Image
        mask_path = os.path.join(TEMPLATE_DIR, "print_mask.png")
        mask = Image.open(mask_path)
        mask_arr = np.array(mask)

        # Lens center should be fully excluded (mask = 0)
        assert mask_arr[LENS_CY, LENS_CX] == 0, \
            "Lens center should be excluded from print mask"

        # Center of print region should be included (mask > 200)
        cx = PRINT_X + PRINT_W // 2
        cy = PRINT_Y + PRINT_H // 2
        assert mask_arr[cy, cx] > 200, \
            "Center of print region should be printable"


# ─── Shadow layer tests (BLOCKER 3 regression) ───────────────────────────

class TestShadowLayer:
    """Verify shadow is physically layered correctly.

    The shadow must sit BELOW the case body and must not darken
    the center of the case (which would indicate the shadow is
    being composited on top).
    """

    def test_case_center_not_darkened_by_shadow(self, template):
        """The center of the case body should not be darkened by shadow.

        If shadow were composited on top of base, the center would be
        darker than the base layer alone. With correct layering
        (shadow below base), the base fully obscures the shadow.
        """
        # Render with just base+shadow (no artwork to distract)
        from core.catalog_models import CaseTemplateLayer, PrintRegion, Canvas
        from core.case_template_loader import CaseTemplate

        tpl = template
        # Use a plain white artwork that fully covers print region
        art = Image.new("RGBA", (1000, 2000), (255, 255, 255, 255))
        result = render_case(art, tpl, template_dir=TEMPLATE_DIR, fit_mode="cover")
        result_arr = np.array(result)

        # Sample center of case body
        cx = CASE_X + CASE_W // 2
        cy = CASE_Y + CASE_H // 2
        center_pixel = _pixel(result_arr, cx, cy)

        # Center should be bright (white art on white base)
        # If shadow were on top, it would noticeably darken the center
        assert center_pixel[0] > 220 and center_pixel[1] > 220, \
            (f"Case center appears too dark — shadow may be composited "
             f"on top instead of below. Pixel: {center_pixel[:3]}")

    def test_shadow_exists_outside_case(self, template):
        """Shadow should be visible outside the case body (right side)."""
        art = Image.new("RGBA", (1000, 2000), (255, 255, 255, 255))
        result = render_case(art, template, template_dir=TEMPLATE_DIR, fit_mode="cover")
        result_arr = np.array(result)

        # Sample a point just outside the straight right edge of the case
        # (midway down, away from corners — shadow is strongest here).
        # Shadow offset = 6px right, blur = 18px.
        sx = CASE_X + CASE_W + 10   # 10px outside right edge
        sy = CASE_Y + CASE_H // 2   # midway down (straight edge, not corner)
        shadow_pixel = _pixel(result_arr, sx, sy)

        # Shadow pixel should have some alpha (it's a soft shadow)
        # and should be dark (black shadow on transparent)
        assert shadow_pixel[3] > 10, \
            "Shadow should be visible outside case body"
        # Shadow should be dark, not bright
        assert shadow_pixel[0] < 100, \
            f"Shadow pixel outside case should be dark, got {shadow_pixel[:3]}"


# ─── Deterministic rendering ──────────────────────────────────────────────

class TestDeterministic:

    def test_re_render_is_identical(self, template):
        """Re-rendering the same artwork must produce identical pixels."""
        art_path = os.path.join(FIXTURES_DIR, "color-block.png")
        art = Image.open(art_path).convert("RGBA")

        r1 = render_case(art, template, template_dir=TEMPLATE_DIR, fit_mode="cover")
        r2 = render_case(art, template, template_dir=TEMPLATE_DIR, fit_mode="cover")

        arr1 = np.array(r1)
        arr2 = np.array(r2)

        assert np.array_equal(arr1, arr2), \
            "Re-render of same input should be pixel-identical"

    def test_all_artworks_deterministic(self, template):
        """Each artwork should produce deterministic output."""
        for name, filename, fit_mode in ARTWORKS:
            art_path = os.path.join(FIXTURES_DIR, filename)
            art = Image.open(art_path).convert("RGBA")

            r1 = render_case(art, template, template_dir=TEMPLATE_DIR, fit_mode=fit_mode)
            r2 = render_case(art, template, template_dir=TEMPLATE_DIR, fit_mode=fit_mode)

            assert np.array_equal(np.array(r1), np.array(r2)), \
                f"{name}: re-render should be identical"


# ─── Template reuse ────────────────────────────────────────────────────────

class TestTemplateReuse:

    def test_all_three_artworks_render(self, template):
        """All three artworks must render successfully through the same template."""
        for name, filename, fit_mode in ARTWORKS:
            art_path = os.path.join(FIXTURES_DIR, filename)
            art = Image.open(art_path).convert("RGBA")
            result = render_case(art, template, template_dir=TEMPLATE_DIR, fit_mode=fit_mode)
            assert result is not None
            assert result.size == (template.canvas.width, template.canvas.height)

    def test_artworks_produce_different_output(self, rendered_outputs):
        """Each artwork should produce a visually different render."""
        names = list(rendered_outputs.keys())
        for i in range(len(names)):
            for j in range(i + 1, len(names)):
                arr_i = rendered_outputs[names[i]]
                arr_j = rendered_outputs[names[j]]
                assert not np.array_equal(arr_i, arr_j), \
                    f"'{names[i]}' and '{names[j]}' produced identical renders"

    def test_template_not_modified_between_renders(self, template):
        """The template object should be the same (immutable) before and after rendering."""
        art_path = os.path.join(FIXTURES_DIR, "color-block.png")
        art = Image.open(art_path).convert("RGBA")

        tpl_id_before = template.id
        tpl_layers_before = len(template.layers)
        tpl_canvas_before = (template.canvas.width, template.canvas.height)

        render_case(art, template, template_dir=TEMPLATE_DIR)

        assert template.id == tpl_id_before
        assert len(template.layers) == tpl_layers_before
        assert (template.canvas.width, template.canvas.height) == tpl_canvas_before


# ─── Visual regression with PNG baselines (BLOCKER 7) ────────────────────

class TestVisualRegression:
    """Visual regression baseline comparison using PNG reference images.

    Baselines are stored as compressed PNGs under
    tests/fixtures/baselines/case-<name>.png.

    IMPORTANT: Baselines are NEVER auto-generated by this test.
    To regenerate baselines, run:

        python scripts/regenerate_case_baselines.py

    This is an explicit developer action to prevent CI from silently
    blessing a changed renderer.
    """

    def test_visual_baseline_match(self, template):
        """Rendered output should match saved baseline within tolerance."""
        for name, filename, fit_mode in ARTWORKS:
            baseline_path = os.path.join(BASELINE_DIR, f"case-{name}.png")

            if not os.path.exists(baseline_path):
                pytest.fail(
                    f"Baseline not found: {baseline_path}. "
                    f"Run 'python scripts/regenerate_case_baselines.py' "
                    f"to generate baselines."
                )

            # Render
            art_path = os.path.join(FIXTURES_DIR, filename)
            art = Image.open(art_path).convert("RGBA")
            result = render_case(art, template, template_dir=TEMPLATE_DIR, fit_mode=fit_mode)
            result_arr = np.array(result).astype(np.int16)

            # Load baseline
            baseline = Image.open(baseline_path).convert("RGBA")
            baseline_arr = np.array(baseline).astype(np.int16)

            assert baseline_arr.shape == result_arr.shape, \
                f"{name}: shape mismatch {result_arr.shape} vs {baseline_arr.shape}"

            # Mean absolute difference across all channels
            diff = np.abs(result_arr - baseline_arr)
            mean_diff = diff.mean()

            assert mean_diff <= VISUAL_TOLERANCE, \
                (f"{name}: visual diff {mean_diff:.2f} exceeds tolerance "
                 f"{VISUAL_TOLERANCE}")

    def test_no_warnings_from_pixel_math(self, template):
        """Pixel arithmetic must not produce uint8 overflow warnings."""
        art_path = os.path.join(FIXTURES_DIR, "color-block.png")
        art = Image.open(art_path).convert("RGBA")
        result = render_case(art, template, template_dir=TEMPLATE_DIR, fit_mode="cover")
        result_arr = np.array(result)

        # Do some typical pixel math that previously caused overflow
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter("always")
            # This should NOT produce RuntimeWarning: overflow
            px = result_arr[500, 500].astype(np.int16)
            base = np.array([248, 247, 245], dtype=np.int16)
            diff = np.abs(px[:3] - base)
            _ = diff.mean()

            overflow_warnings = [
                x for x in w
                if issubclass(x.category, RuntimeWarning)
                and "overflow" in str(x.message).lower()
            ]
            assert len(overflow_warnings) == 0, \
                f"Pixel math produced overflow warnings: {overflow_warnings}"
